version: "3"

services:
    HostA:
        build: ./base-image
        image: nees-base-image
        container_name: host-172.16.10.5
        tty: true
        cap_add:
                - ALL
        networks:
            net-172.16.10.0:
                ipv4_address: 172.16.10.5

    HostB:
        build: ./base-image   
        image: nees-base-image
        container_name: host-172.16.10.6
        tty: true
        cap_add:
                - ALL
        networks:
            net-172.16.10.0:
                ipv4_address: 172.16.10.6
networks:
    net-172.16.10.0:
        name: net-172.16.10.0
        ipam:
            config:
                - subnet: 172.16.10.0/24
