---
version: "3"
services:
  http:
    build:
      context: ./nginx
    image: nginx/alpine
    container_name: web-server
    volumes:
      - ./nginx/iweb:/usr/share/nginx/html
    tty: true
    cap_add:
        - ALL
    networks:
      net-172.16.10.0:
          ipv4_address: 172.16.10.100
    ports:
      - 5025:80
  client:
    build: 
      context: ./client
    image: alpine-vnc-wireshark
    container_name: wireshark
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true
    ports:
      - 5900:5900
      - 2222:22
    networks:
      net-172.16.10.0:
          ipv4_address: 172.16.10.10

networks:
    net-172.16.10.0:
        name: net-172.16.10.0
        ipam:
            config:
                - subnet: 172.16.10.0/24
