---
version: "3"
services:
  wireshark:
#    build:
#      context: ./wireshark
    image: linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    networks:
      net-172.16.10.0:
          ipv4_address: 172.16.10.10
    ports:
      - 3128:3000 #optional
    restart: unless-stopped
  http:
    build:
      context: ./httpd
    image: httpd-image
    container_name: web-server
    tty: true
    cap_add:
        - ALL
    networks:
      net-172.16.10.0:
          ipv4_address: 172.16.10.100
    ports:
      - 5000:3000
networks:
    net-172.16.10.0:
        name: net-172.16.10.0
        ipam:
            config:
                - subnet: 172.16.10.0/24
