---
version: "3"
services:
  sniffer:
    build: 
      context: ./sniffer
    image: aled-image   # Alpine edge image
    container_name: sniffer-host
    tty: true
    cap_add:
        - ALL
    privileged: true
    volumes:
        - ./source:/mapdir
    network_mode: host
  client:
    build:
      context: ./client
    image: cli-image
    container_name: client-host
    tty: true
    cap_add:
        - ALL
    networks:
      net-172.16.10.0:
          ipv4_address: 172.16.10.10
  apache:
    build:
      context: ./apache
    image: kalicki2k/alpine-apache-php
    container_name: apache-server
    volumes:
      - ./apache/www:/var/www/localhost/
    tty: true
    cap_add:
        - ALL
    networks:
      net-172.16.10.0:
          ipv4_address: 172.16.10.100
    ports:
      - 5050:80

networks:
    net-172.16.10.0:
        name: net-172.16.10.0
        ipam:
            config:
                - subnet: 172.16.10.0/24
